local library = loadstring(game:HttpGet(('https://raw.githubusercontent.com/AikaV3rm/UiLib/master/Lib.lua')))()

local w = library:CreateWindow("Storm Hub") -- Creates the window

local b = w:CreateFolder("")

local v = w:CreateFolder("Visual")

local c = w:CreateFolder("Credits")

local g = w:CreateFolder("Give")

local p = w:CreateFolder("Player")

local t = w:CreateFolder("Tp")

local Espplayer = true

local Jum = true

local noc = true

local noc = false

local Jum = false

local hel = true

local hel = false

local Runfast = true

local Runfast = false

local Espplayer = false-- Creates the folder(U will put here your buttons,etc)

b:Label("Pretty Useless NGL",{
    TextSize = 25; -- Self Explaining
    TextColor = Color3.fromRGB(255,255,255); -- Self Explaining
    BgColor = Color3.fromRGB(69,69,69); -- Self Explaining
    
}) 

b:Button("Button",function()
    print("Elym Winning")
end)

g:Button("Give Pizza",function()
    print("Made by Axon#2433")
   print("Made by Axon#2433")
   -- Script generated by SimpleSpy - credits to exxtremewa#9394
-- This generator is IN DEVELOPMENT, not compatible with all types/classes yet

function getNil(name,class) for _,v in pairs(getnilinstances())do if v.ClassName==class and v.Name==name then return v;end end end

local args = {
    [1] = "Pizza1",
}

game:GetService("ReplicatedStorage").RemoteEvents.GiveTool:FireServer(unpack(args))
end)

g:Button("Give Cookie",function()
    print("Made by Axon#2433")
    print("Made by Axon#2433")
    -- Script generated by SimpleSpy - credits to exxtremewa#9394
-- This generator is IN DEVELOPMENT, not compatible with all types/classes yet

function getNil(name,class) for _,v in pairs(getnilinstances())do if v.ClassName==class and v.Name==name then return v;end end end

local args = {
    [1] = "Cookie",
}

game:GetService("ReplicatedStorage").RemoteEvents.GiveTool:FireServer(unpack(args))
end)

p:Toggle("Walk fast",function(bool)
    print("Axon Winnig")
    print("Made by Axon#2433")
    shared.toggle = bool
    print(shared.toggle)
    Runfast = bool
    if Runfast == true then 
        game.Players.LocalPlayer.Character.Humanoid.WalkSpeed = 50
    end
        if Runfast == false then 
        game.Players.LocalPlayer.Character.Humanoid.WalkSpeed = 14
        end
end)

p:Toggle("No clip",function(bool)
    print("Axon Winnig")
    print("Made by Axon#2433")
    shared.toggle = bool
    print(shared.toggle)
    noc = bool
    if noc == true then 
        noclip = false
game:GetService('RunService').Stepped:connect(function()
if noclip then
game.Players.LocalPlayer.Character.Humanoid:ChangeState(11)
end
end)
plr = game.Players.LocalPlayer
mouse = plr:GetMouse()

noclip = not noclip
game.Players.LocalPlayer.Character.Humanoid:ChangeState(11)
    end
        if noc == false then 
        noclip = not noclip
game.Players.LocalPlayer.Character.Humanoid:ChangeState(11)
        end
end)

p:Toggle("Inf Health",function(bool)
    shared.toggle = bool
    print(shared.toggle)
    hel = bool
        if hel == true then 
        game.Players.LocalPlayer.Character.Humanoid.Health = 50000
        game.Players.LocalPlayer.Character.Humanoid.HealthDisplayDistance = 500
        game.Players.LocalPlayer.Character.Humanoid.MaxHealth = 50000
    end
        if hel == false then 
        game.Players.LocalPlayer.Character.Humanoid.Health = 100
        game.Players.LocalPlayer.Character.Humanoid.HealthDisplayDistance = 100
        game.Players.LocalPlayer.Character.Humanoid.MaxHealth = 100
        end
end)

p:Toggle("Jump high",function(bool)
    shared.toggle = bool
    print(shared.toggle)
    Jum = bool
        if Jum == true then 
        game.Players.LocalPlayer.Character.Humanoid.JumpPower = 140
    end
        if Jum == false then 
        game.Players.LocalPlayer.Character.Humanoid.JumpPower = 50
        end
end)

b:Slider("Slider",{
    min = 10; -- min value of the slider
    max = 50; -- max value of the slider
    precise = true; -- max 2 decimals
},function(value)
    print(value)
end)

t:Button("Tp to Shop",function()
    print("Made by Axon#2433")
    print("Axon Winnig")
        game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = CFrame.new(-414.614563, 2.56200147, -101.802498, -0.22145398, -0.0108732861, 0.975110114, -0.0490423255, 0.998796701, -4.26675143e-07, -0.973936737, -0.0478217639, -0.221720755)
end)

c:Button("Click me for Credits",function()
    print("Made by Axon#2433")
    print("Axon Winnig")
    game.StarterGui:SetCore('SendNotification', {
        Title    = 'Credits',
        Text     = ('made by Axon#2433.'),
        Icon    = ('http://www.roblox.com/asset/?id=6710773193'),
        Duration = 9999,
    })
    
end)

t:Button("Tp to House",function()
    print("Made by Axon#2433")
    print("Axon Winnig")
        game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = CFrame.new(-36.8511467, 2.1805439, -193.708817, 0.996046305, 0.0167951547, 0.0872336999, -0.0172780361, 0.999839306, 0.00478341104, -0.0871393383, -0.00627171481, 0.996176422)
end)

g:Button("Give Apple",function()
    print("Made by Axon#2433")
    print("Axon Winnig")
    -- Script generated by SimpleSpy - credits to exxtremewa#9394
-- This generator is IN DEVELOPMENT, not compatible with all types/classes yet

function getNil(name,class) for _,v in pairs(getnilinstances())do if v.ClassName==class and v.Name==name then return v;end end end

local args = {
    [1] = "Apple",
}

game:GetService("ReplicatedStorage").RemoteEvents.GiveTool:FireServer(unpack(args))
end)

b:Dropdown("Dropdown",{"A","B","C"},true,function(mob) --true/false, replaces the current title "Dropdown" with the option that t
    print(mob)
end)

b:Bind("Bind",Enum.KeyCode.C,function() --Default bind
    print("Yes")
end)

b:ColorPicker("ColorPicker",Color3.fromRGB(255,0,0),function(color) --Default color
    print(color)
end)

b:Box("Box","number",function(value) -- "number" or "string"
    print(value)
end)
